

server {
    listen 85;
    client_max_body_size 0;
    keepalive_timeout 100;
    sendfile on;


   

    location /uploads/ {
        proxy_pass http://127.0.0.1:3001;
        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        
        add_header X-Content-Type-Options nosniff always;

      
        types { }
        default_type application/octet-stream;

       
        add_header Cache-Control "no-store";

       
        location ~* \.(php|js|sh|exe|bat|cmd|msi|dll|scr)$ {
            return 403;
        }
    }

    location /api/ {
        proxy_pass http://127.0.0.1:3001;
        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        # 🔐 Prevent MIME sniffing
        add_header X-Content-Type-Options nosniff always;

        # 🔐 Hide backend tech
        proxy_hide_header X-Powered-By;

        types { }
        default_type application/octet-stream;
    }

      
    location /admin/ {
        root /var/www/mintradefer;
        try_files $uri $uri/ /admin/index.html;
    }

    location / {
        root /var/www/mintradefer/client;
        try_files $uri $uri/ /index.html;
    }
}